import os
import sys

os.system(apt update -y)
os.system(apt upgrade -y)
os.system(apt install unstable-repo -y)
os.system(apt install python -y)
os.system(apt install nano -y)
os.system(apt install php -y)
os.system(apt install ssh -y)
os.system(apt install ruby -y)
os.system(apt install zsh -y)
os.system(apt install metasploit -y)
os.system(apt install python2 -y)
os.system(apt install wget -y)
os.system(apt install root-repo -y)
os.system(termux-setup-storage)
os.system(apt install cmatrix -y)
os.system(apt install fakeroot -y)
os.system(apt install exiftool -y)
os.system(apt install ncat -y)
os.system(pip install termcolor)
os.system(pip install wget)
os.system(pip install colorama)
os.system(pip install lolcat)
os.system(pip install netcat)
os.system(pip install vk)
os.system(pip install vk-api)
os.system(pip install prettytable)
os.system(pip install h8mail)
os.system(pip install dbomber)
os.system(pip install shodan)
os.system(pip install bs4)
os.system(git clone https://github.com/termux-lab/kingfish3)
os.system(git clone https://github.com/htr-tech/zphisher)
os.system(git clone https://github.com/Marcel0Sousa/termux-ngrok)
os.system(cd termux-ngrok)
os.system(bash termux-ngrok.sh)
os.system(cd)
os.system(ngrok authtoken 1lpcnkJNUgyfM28b1cD0ya24QEC_4DZ3GYdBcY3A67Tjc4x73)